[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pentest-toolbox"
version = "0.1.0"
authors = [{name = "Your Name", email = "your.email@example.com"}]
description = "A brief description of your project"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.6"

dependencies = [
  "requests >=2.0",
  "scapy >=2.4",
  "gitpython",
  "argparse",
  "hashlib",
  "socket",
  "random",
  "sys"
]

[project.urls]
homepage = "https://example.com/"
repository = "https://example.com/repo"
documentation = "https://example.com/docs"

[project.scripts]

